# utils/initial_data.py

initial_data = [
{'id': 503919,
  'name': 'The Lighthouse',
  'year': 2019,
  'summary': 'The hypnotic and hallucinatory tale of two lighthouse keepers on a remote and mysterious New England island in the 1890s.',
  'slug': 'the-lighthouse-2019',
  'poster_url': 'https://image.tmdb.org/t/p/w185/3nk9UoepYmv1G9oP18q6JJCeYwN.jpg'},
 {'id': 475557,
  'name': 'Joker',
  'year': 2019,
  'summary': 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
  'slug': 'joker-2019',
  'poster_url': 'https://image.tmdb.org/t/p/w185/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg'},
 {'id': 530385,
  'name': 'Midsommar',
  'year': 2019,
  'summary': "A couple travels to Sweden to visit a rural hometown's fabled mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.",
  'slug': 'midsommar-2019',
  'poster_url': 'https://image.tmdb.org/t/p/w185/rXsh4MI6uyVgZBSSzXCfitJnVPy.jpg'},
 {'id': 531428,
  'name': 'Portrait of a Lady on Fire',
  'year': 2019,
  'summary': 'On an isolated island in Bretagne at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.',
  'slug': 'portrait-of-a-lady-on-fire-2019',
  'poster_url': 'https://image.tmdb.org/t/p/w185/3NTEMlG5mQdIAlKDl3AJG0rX29Z.jpg'},
 {'id': 426426,
  'name': 'Roma',
  'year': 2018,
  'summary': "A year in the life of a middle-class family's maid in Mexico City in the early 1970s.",
  'slug': 'roma-2018',
  'poster_url': 'https://image.tmdb.org/t/p/w185/dtIIyQyALk57ko5bjac7hi01YQ.jpg'},
 {'id': 157336,
  'name': 'Interstellar',
  'year': 2014,
  'summary': "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
  'slug': 'interstellar-2014',
  'poster_url': 'https://image.tmdb.org/t/p/w185/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg'},
 {'id': 245891,
  'name': 'John Wick ',
  'year': 2014,
  'summary': 'An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him.',
  'slug': 'john-wick-2014',
  'poster_url': 'https://image.tmdb.org/t/p/w185/5vHssUeVe25bMrof1HyaPyWgaP.jpg'},
 {'id': 56831,
  'name': 'The Sunset Limited ',
  'year': 2011,
  'summary': "Two men in an apartment with their opposing beliefs in this play by Cormac McCarthey. The black guy, a former convict who believes in God, just saved the white agnostic professor from jumping in front of the express train. He won't let the depressed man leave, without following him, and feel he's in this situation for a reason, decided by God. An intense chamber play about belief or unbelief, and a conversation about what's true and important in life, or not.",
  'slug': 'the-sunset-limited-2011',
  'poster_url': 'https://image.tmdb.org/t/p/w185/vv5aU4ed63nWPCrXfnxd40Gx7fQ.jpg'},
 {'id': 50014,
  'name': 'The Help ',
  'year': 2011,
  'summary': "Set in Mississippi during the 1960s, Skeeter (Stone) is a southern society girl who returns from college determined to become a writer, but turns her friends' lives -- and a Mississippi town -- upside down when she decides to interview the black women who have spent their lives taking care of prominent southern families. Aibileen (Davis), Skeeter's best friend's housekeeper, is the first to open up -- to the dismay of her friends in the tight-knit black community. Despite Skeeter's life-long friendships hanging in the balance, she and Aibileen continue their collaboration and soon more women come forward to tell their stories -- and as it turns out, they have a lot to say. Along the way, unlikely friendships are forged and a new sisterhood emerges, but not before everyone in town has a thing or two to say themselves when they become unwittingly -- and unwillingly -- caught up in the changing times.",
  'slug': 'the-help-2011',
  'poster_url': 'https://image.tmdb.org/t/p/w185/6u85CuvnbrzWMhKbGk4Bm5RnO3V.jpg'},
 {'id': 34647,
  'name': 'Enter the Void ',
  'year': 2009,
  'summary': "Tokyo's nasty underside, seen primarily through the eyes of Oscar, a heavy drug user, whose sister Linda is a stripper. Oscar also has flashbacks to his childhood when trauma upends the siblings. Oscar's drug-fed hallucinations alter Tokyo's already-disconcerting nights, and after the police shoot him, he can float above and look down: on his sister's sorrow, on the rooms of a love hotel, and on life at even a molecular level. The spectrum's colors can be beautiful; it's people's colorless lives that can be ugly. And what of afterlife, is there more than a void?",
  'slug': 'enter-the-void-2009',
  'poster_url': 'https://image.tmdb.org/t/p/w185/AvD7oAOit8FZYG1fH2GA5SPLDst.jpg'},
 {'id': 453,
  'name': 'Beautiful Mind, A ',
  'year': 2001,
  'summary': 'From the heights of notoriety to the depths of depravity, John Forbes Nash, Jr. experienced it all. A mathematical genius, he made an astonishing discovery early in his career and stood on the brink of international acclaim. But the handsome and arrogant Nash soon found himself on a painful and harrowing journey of self-discovery. After many years of struggle, he eventually triumphed over his tragedy, and finally - late in life - received the Nobel Prize.',
  'slug': 'beautiful-mind-a-2001',
  'poster_url': 'https://image.tmdb.org/t/p/w185/hGBgv2Ir3t1wMP1Xp5CAQXArkV9.jpg'},
 {'id': 603,
  'name': 'The Matrix',
  'year': 1999,
  'summary': "The best known work of the Wachowski's, which has benefited much from the literature of philosophy and questioned reality itself from a descartesian point of view, and also touched on the dilemma of freedom and anthropogenic attitude of humanity towards everythings.\r\nThomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.",
  'slug': 'the-matrix-1999',
  'poster_url': 'https://image.tmdb.org/t/p/w185/lZpWprJqbIFpEV5uoHfoK0KCnTW.jpg'},
 {'id': 62,
  'name': '2001: A Space Odyssey',
  'year': 1968,
  'summary': '"2001" is a story of evolution. Sometime in the distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere throughout the universe as well). Evolution then enabled humankind to reach the moon\'s surface, where yet another monolith is found, one that signals the monolith placers that humankind has evolved that far. Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers. The winner will achieve the next step in evolution, whatever that may be.',
  'slug': '2001-a-space-odyssey-1968',
  'poster_url': 'https://image.tmdb.org/t/p/w185/90T7b2LIrL07ndYQBmSm09yqVEH.jpg'},
 {'id': 389,
  'name': '12 Angry Men ',
  'year': 1957,
  'summary': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.",
  'slug': '12-angry-men-1957',
  'poster_url': 'https://image.tmdb.org/t/p/w185/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg'}]